# Server
server:
  port: 8999

# Logging
logging:
  config: classpath:logback-dev.xml

# Application Configuration
appConfigs:
  cors:
    enabled: true
    pathPattern: /api/**
    allowedOrigins:
      - http://localhost:8686
      - http://localhost:8787
    allowedMethods:
      - DELETE
      - GET
      - POST
      - PUT
    exposedHeaders:
      - Authorization
    allowCredentials: true
